### ISSUE TITLE
I generated the token as required, but after calling, I prompted "An error occurred while attempting to decode the Jwt: Failed to validate the token"

### ISSUE THREAD

**Issue by namehuxing** [gregwhitaker/springboot-rsocketjwt-example#2]
![image](https://user-images.githubusercontent.com/7345460/102691454-a8fa0180-4247-11eb-951e-72f695126872.png)
![image](https://user-images.githubusercontent.com/7345460/102691463-bd3dfe80-4247-11eb-9d9a-df9806d49ba5.png)
gradlew :hello-client:bootRun --args="--token {eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiYXVkIjoiaGVsbG8tc2VydmljZSIsInNjb3BlIjoiVVNFUiIsImlzcyI6ImhlbGxvLXNlcnZpY2UtZGVtbyIsImV4cCI6MTYwODM4ODM2OSwianRpIjoiMDUwMTRkZGMtMTZmMS00OWY3LWI2ZjUtODlkNGE1OGRmNGVhIn0.1BrHEllAjq6LBrA1pRdmuZAEk3r7k3QsEBqOin7ajhs} hello.secure.adminonly Bob"
![image](https://user-images.githubusercontent.com/7345460/102691471-cd55de00-4247-11eb-8890-4fa6df02dc88.png)

**Comment by gregwhitaker** [comment]
Remove the curly braces from around the token in the command.

Should be like this:
```
gradlew :hello-client:bootRun --args="--token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiYXVkIjoiaGVsbG8tc2VydmljZSIsInNjb3BlIjoiVVNFUiIsImlzcyI6ImhlbGxvLXNlcnZpY2UtZGVtbyIsImV4cCI6MTYwODM4ODM2OSwianRpIjoiMDUwMTRkZGMtMTZmMS00OWY3LWI2ZjUtODlkNGE1OGRmNGVhIn0.1BrHEllAjq6LBrA1pRdmuZAEk3r7k3QsEBqOin7ajhs hello.secure.adminonly Bob"
```
